apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  template:
    metadata:
      labels:
        app: demo-app
        version: stable
  replicas: 2
  strategy:
    canary:
      # stableService: dev-demo-app-stable
      # canaryService: dev-demo-app-canary
      
      trafficRouting:
        istio:
          virtualService:
            name: dev-demo-app
          destinationRule:
            name: dev-demo-app

      steps:
      - setWeight: 20
      - pause:
          duration: 1m
      - setWeight: 50
      - pause:
          duration: 1m
      - setWeight: 100