apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: canary-demo
  labels:
    app: demo-app
    service: demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: demo-app

# Made with Bob
