apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canary-demo

resources:
- ../../base

labels:
- pairs:
    environment: production
    tier: production

patches:
- path: rollout-patch.yaml
- path: resources-patch.yaml

images:
- name: docker.io/siravichibm123/demo-app
  newTag: v1.0.0

configMapGenerator:
- name: demo-app-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=warn
  - ENABLE_DEBUG=false
  - ENABLE_METRICS=true

# Made with Bob
